security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            # the 'entry_point option used for deciding behavior when anon user attempt to get access for private resource'
            entry_point: App\Security\EntryPointRedirection
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
