swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host: '%env(MAILER_HOST)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASSWORD)%'
    port: 465
    #    spool: { type: memory }
    encryption: ssl
    auth_mode: login
    logging: '%kernel.debug%'
